# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f305d49636f64618f06c524fd4c168f3aa25dbdc1817b8d94a05f840690fb4b1b5ea1cc72b1df015e6aa65bd0ab587df13bcb0141a888c85aa0531c0e0cfdad

test:
  secret_key_base: 46073abf77b88ba448dcc820e9abf6531aa0dceba26e4a52c335ff308310d14abfd6c6328e9195961aef3e07c2ea226dd4971fd88424e609fb66a60ac5c588a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
